/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Automoviles;

/**
 *
 * @author Stephannie
 */
public class FRM_Automoviles extends javax.swing.JFrame {
    
    Controlador_FRM_Automoviles controladorAutomoviles;

    /**
     * Creates new form FRM_Automoviles
     */
    public FRM_Automoviles() {
        initComponents();
        setVisible(false);
        controladorAutomoviles=new Controlador_FRM_Automoviles(this);
        gUI_Botones1.agregarEventos(controladorAutomoviles);
    }
    
    public String[] devolverInfo(){
        return this.gUI_InfoAuto1.devolverInfo();
    }
    
    public String devolverNumeroCodigo(){
        return this.gUI_InfoAuto1.devolverNumeroCodigo();
    }
    
        public void estadoInicial(){
        this.gUI_Botones1.estadoInicial();
        this.gUI_InfoAuto1.estadoInicial();
    }
    
    public void mostrarInfo(String arreglo[]){
        this.gUI_InfoAuto1.mostrarInfo(arreglo);
    }
    
    public void habilitarBotones(){
        this.gUI_Botones1.habilitarBotones();
    }
    
    public void habilitarTexto(){
        this.gUI_InfoAuto1.habilitarTexto();
    }
    
    public void deshabilitarBuscar(){
        this.gUI_Botones1.deshabilitarBuscar();
    }
        
    public void habilitarBuscar(){
        this.gUI_Botones1.habilitarBuscar();
    }
    
    public void deshabilitarAgregar(){
        this.gUI_Botones1.deshabilitarAgregar();
    }
    
    public void limpiarInterfaz(){
        this.gUI_InfoAuto1.limpiarInterfaz();
    }
    
    public void deshabilitarNumCodigo(){
        this.gUI_InfoAuto1.deshablitarNumCodigo();
    }
    
    public void limpiarInterfazParaModificar(){
        this.gUI_InfoAuto1.limpiarInterfazParaModificar();
    }
    
     public void habilitarNumCodigo(){
        this.gUI_InfoAuto1.habilitarNumCodigo();
    }
     
     public void llamarBuscar(){
         controladorAutomoviles.buscar();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InfoAuto1 = new Vista.GUI_InfoAuto();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(gUI_InfoAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InfoAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InfoAuto gUI_InfoAuto1;
    // End of variables declaration//GEN-END:variables
}
