/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Automoviles;

/**
 *
 * @author Stephannie
 */
public class GUI_Botones extends javax.swing.JPanel {
    
//Ref
    Controlador_FRM_Automoviles controladorAutos;
    /**
     * Creates new form GUI_Botones
     */
    public GUI_Botones() {
        initComponents();
    }
    
    public void agregarEventos(Controlador_FRM_Automoviles controladorAutos){
        this.controladorAutos=controladorAutos;
        this.btn_agregar.addActionListener(controladorAutos);
        this.btn_buscar.addActionListener(controladorAutos);
        this.btn_eliminar.addActionListener(controladorAutos);
        this.btn_modificar.addActionListener(controladorAutos);
    }

     public void estadoInicial(){
        this.btn_agregar.setEnabled(false);
        this.btn_modificar.setEnabled(false);
        this.btn_eliminar.setEnabled(false);
    }
     
     public void habilitarBotones(){
        this.btn_eliminar.setEnabled(true);
        this.btn_agregar.setEnabled(true);
        this.btn_modificar.setEnabled(true);
    }
     
     public void deshabilitarAgregar(){
          this.btn_agregar.setEnabled(false);
     }
     
     public void devolverBotonBuscar(){
         this.btn_buscar.doClick();
     }
     
     public void deshabilitarBuscar(){
         this.btn_buscar.setEnabled(false);
     }
     
     public void habilitarBuscar(){
         this.btn_buscar.setEnabled(true);
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buscar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        btn_buscar.setText("Buscar");

        btn_agregar.setText("Agregar");

        btn_modificar.setText("Modificar");

        btn_eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_buscar)
                .addGap(18, 18, 18)
                .addComponent(btn_agregar)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_agregar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    // End of variables declaration//GEN-END:variables
}
