/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Automoviles;
import java.awt.event.KeyEvent;


/**
 *
 * @author Stephannie
 */
public class GUI_InfoAuto extends javax.swing.JPanel {
    
    //ref
    Controlador_FRM_Automoviles controladorAutos;
    GUI_Botones botones;
    /**
     * Creates new form GUI_InfoAuto
     */
    public GUI_InfoAuto() {
        initComponents();
        botones=new GUI_Botones();
    }
    
    public String[] devolverInfo(){
        String arreglo[];
        arreglo=new String[4];
        arreglo[0]=this.jt_numero.getText();
        arreglo[1]=this.jt_nombre.getText();
        arreglo[2]=this.jt_cedula.getText();
        arreglo[3]=this.jt_placa.getText();
        
        return arreglo;
    }

    public String devolverNumeroCodigo(){
        return this.jt_numero.getText();
    }
    
    public void mostrarInfo(String arreglo[]){
        this.jt_nombre.setText(arreglo[0]);
        this.jt_cedula.setText(arreglo[1]);
        this.jt_placa.setText(arreglo[2]);
    }
    
    public void limpiarInterfaz(){
        this.jt_cedula.setText("");
        this.jt_nombre.setText("");
        this.jt_numero.setText("");
        this.jt_placa.setText("");
    }
    
    public void deshablitarNumCodigo(){
        this.jt_numero.setEnabled(false);
    }
    
    public void limpiarInterfazParaModificar(){
        this.jt_cedula.setText("");
        this.jt_nombre.setText("");
        this.jt_placa.setText("");
    }
    
    public void habilitarNumCodigo(){
    this.jt_numero.setEnabled(true);
    }
    
    public void estadoInicial(){
        this.jt_cedula.setEnabled(false);
        this.jt_nombre.setEnabled(false);
        this.jt_placa.setEnabled(false);
    }
    
    public void habilitarTexto(){
        this.jt_cedula.setEnabled(true);
        this.jt_nombre.setEnabled(true);
        this.jt_placa.setEnabled(true);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_numero = new javax.swing.JLabel();
        jt_numero = new javax.swing.JTextField();
        jl_nombre = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jl_cedula = new javax.swing.JLabel();
        jt_cedula = new javax.swing.JTextField();
        jl_placa = new javax.swing.JLabel();
        jt_placa = new javax.swing.JTextField();

        jl_numero.setText("Número de registro:");

        jt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_numeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_numeroKeyTyped(evt);
            }
        });

        jl_nombre.setText("Nombre dueño:");

        jl_cedula.setText("Cédula dueño:");

        jl_placa.setText("Número de placa:");

        jt_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_placaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_numero)
                            .addComponent(jl_nombre)
                            .addComponent(jl_cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_numero)
                            .addComponent(jt_nombre)
                            .addComponent(jt_cedula)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_placa)
                        .addGap(18, 18, 18)
                        .addComponent(jt_placa, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero)
                    .addComponent(jt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cedula)
                    .addComponent(jt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_placa)
                    .addComponent(jt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_numeroKeyPressed
       char teclaPresionada=evt.getKeyChar();
           if(teclaPresionada==KeyEvent.VK_ENTER){
              botones.devolverBotonBuscar();
           }
    }//GEN-LAST:event_jt_numeroKeyPressed

    private void jt_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_numeroKeyTyped
           char teclaPresionada=evt.getKeyChar();
           if(teclaPresionada==KeyEvent.VK_ENTER){
              botones.devolverBotonBuscar();
           }
    }//GEN-LAST:event_jt_numeroKeyTyped

    private void jt_placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_placaKeyTyped
        // TODO add your handling code here:
        char teclaPresionada=evt.getKeyChar();
           if(teclaPresionada==KeyEvent.VK_ENTER){
              botones.devolverBotonBuscar();
           }
    }//GEN-LAST:event_jt_placaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_cedula;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_numero;
    private javax.swing.JLabel jl_placa;
    private javax.swing.JTextField jt_cedula;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_numero;
    private javax.swing.JTextField jt_placa;
    // End of variables declaration//GEN-END:variables
}
